language: java
jdk: oraclejdk8
branches:
  only:
  - master
  - develop
sudo: false
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
install: true
addons:
  sonarqube:
    token:
      secure: $SONAR_SECURITY_TOKEN
    branches:
      - master
      - develop
script:
  - mvn clean
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"
