language: java
jdk: oraclejdk8
#branches:
#  only:
#    - master
#    - develop
sudo: true 
before_install:
  - echo "installing private repository"
  - git clone $PRIVATE_REPO_URL_UN_PW jpo-ode-private 
  - cd jpo-ode-private
  - mvn clean
  - mvn install
  - cd ..
install: true #must disable pre-installation of dependencies because it fails due to missing oss.runtime dependency install 
addons:
  sonarqube:
    token:
      secure: $SONAR_SECURITY_TOKEN
    branches:
      - .* 
script:
  - mvn -e clean org.jacoco:jacoco-maven-plugin:prepare-agent
after_success:
  - mvn -e sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.organization=default -Dsonar.login=$SONAR_SECURITY_KEY
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"
