language: java
jdk: oraclejdk8
#branches:
#  only:
#    - master
#    - develop
sudo: true 
before_install:
  - echo "installing private repository"
  - git clone $PRIVATE_REPO_URL_UN_PW jpo-ode-private 
  - cd jpo-ode-private
  - mvn clean
  - mvn install
  - cd ..
install: true #must disable pre-installation of dependencies because it fails due to missing oss.runtime dependency install 
addons:
  sonarqube:
    organization: default
    token:
      secure: $SONAR_SECURITY_TOKEN
    branches:
      - .* 
script:
  #- mvn clean
  #- mvn -e org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
  - mvn -e -U clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"
