swagger: '2.0'
info:
  title: ODE REST API
  description: >-
    Description of functions available from the Operational Data Environment
    (ODE) via RESTful interface.
  version: 0.0.1
host: yourhostname
schemes:
  - https
basePath: /
produces:
  - application/json
paths:
  /tim:
    post:
      summary: >-
        Submit Traveler Information Message (TIM) for broadcast to Connected
        Vehicles.
      operationId: tim_post
      description: >-
        The TIM endpoint accepts a TravelerInputData from which it constructs a
        Traveler Information Message message and sends it to all specified RSUs
        and SDW.
      parameters:
        - name: TravelerInputData
          in: body
          description: >-
            Message containing the parameters for a Traveler Information Message
            including delivery information.
          required: true
          schema:
            $ref: '#/definitions/TravelerInputData'
      tags:
        - TIM
      responses:
        '200':
          description: TravelerInputData was submitted successfully
          schema:
            type: array
            items:
              $ref: '#/definitions/tim'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /RSU SNMP:
    get:
      summary: RSU SNMP Query
      operationId: Send SNMP Messages
      description: Check the health and status of RSU devices through SNMP communication
      parameters:
        - name: IP
          in: query
          description: IP address of an RSU
          required: true
          type: number
          format: string
        - name: OID
          in: query
          description: OID of the attribute you wish to check on
          required: true
          type: number
          format: string
      tags:
        - SNMP
      responses:
        '200':
          description: OID responses
        '400':
          description: Value input error
  /pdm:
    post:
      summary: PDM Interface
      operationId: Send pdm message
      description: |
        The PDM endpoint returns a constructed PDM message
      parameters:
        - name: ProbeDataManagement
          in: body
          description: PDM Message
          required: true
          schema:
            $ref: '#/definitions/ProbeDataManagement'
      tags:
        - PDM
      responses:
        '200':
          description: >-
            A list of RSUs with a success status, and 0 as the error status
            code.
        '400':
          description: >-
            If RSU responds but deposit fails, then it returns snmp error
            status. If RSU does not respond, then it returns empty response
            error.
definitions:
  tim:
    type: object
    properties:
      msgCnt:
        type: integer
      timestamp:
        type: integer
      packetId:
        type: integer
      urlB:
        type: string
        description: UrlB
      dataFrames:
        type: array
        items:
          $ref: '#/definitions/TravelerDataFrame'
      snmp:
        $ref: '#/definitions/SNMP'
      sdw:
        $ref: '#/definitions/SDW'
  TravelerInputData:
    type: object
    properties:
      tim:
        $ref: '#/definitions/tim'
      rsus:
        type: array
        items:
          $ref: '#/definitions/RSU'
      snmp:
        $ref: '#/definitions/SNMP'
      sdw:
        $ref: '#/definitions/SDW'
  ProbeDataManagement:
    type: object
    properties:
      ode:
        $ref: '#/definitions/Ode'
      pdm:
        $ref: '#/definitions/PDM'
      rsuList:
        type: array
        items:
          $ref: '#/definitions/RSU'
  Ode:
    type: object
    properties:
      version:
        type: integer
  TravelerDataFrame:
    type: object
    required:
      - sspindex
    properties:
      sspindex:
        type: integer
        description: >-
          The SSP index is used to control the data elements that follow the
          occurrence of the index. The index relates back to the SSP contents in
          the CERT used to declare what content is allowed by that CERT. In the
          absence of a matching index in the message sender’s CERT, the message
          contents are not valid.
      frameType:
        type: integer
      msgID:
        type: string
      position:
        $ref: '#/definitions/J2735Position3D'
      viewAngle:
        type: string
      mutcd:
        type: integer
      crc:
        type: integer
      startDateTime:
        type: string
      durationTime:
        type: integer
      priority:
        type: integer
      sspLocationRights:
        type: integer
      sspMsgTypes:
        type: integer
      sspMsgContent:
        type: integer
      content:
        type: string
      items:
        type: array
        items:
          $ref: '#/definitions/ITISObj'
      region:
        $ref: '#/definitions/Region'
  Region:
    type: object
    properties:
      name:
        type: string
      regulatorID":
        type: integer
      segmentId:
        type: integer
      anchor_lat:
        type: integer
      anchor_long:
        type: integer
      anchor_eleveation:
        type: integer
      laneWidth:
        type: integer
      directionality:
        type: integer
      closedPath:
        type: string
      direction:
        type: string
      description:
        type: string
      path:
        $ref: '#/definitions/Path'
      oldRegion:
        $ref: '#/definitions/OldRegion'
      geometry:
        $ref: '#/definitions/Geometry'
      content:
        type: string
      itemss:
        type: array
        items:
          type: integer
  ComputedLane:
    type: object
    properties:
      laneID:
        type: integer
      offsetSmallX:
        type: integer
      offsetLargeX:
        type: integer
      offsetSmallY:
        type: integer
      offsetLargeY:
        type: integer
      angle:
        type: integer
      xScale:
        type: integer
      yScale:
        type: integer
  Path:
    type: object
    properties:
      type:
        type: string
      scale:
        type: integer
      nodes:
        type: array
        items:
          $ref: '#/definitions/NodeXY'
      computedLane:
        $ref: '#/definitions/ComputedLane'
  Attribute:
    type: object
    properties:
      localNodes:
        type: array
        items:
          type: integer
      disabledLists:
        type: array
        items:
          type: integer
      enabledLists:
        type: array
        items:
          type: integer
      dataLists:
        type: array
        items:
          $ref: '#/definitions/DataList'
      dWidth:
        type: integer
      dEleveation:
        type: integer
  DataList:
    type: object
    properties:
      pathEndpointAngle:
        type: integer
      laneCrownCenter:
        type: integer
      laneCrownRight:
        type: integer
      laneCrownLeft:
        type: integer
      laneAngle:
        type: integer
      speedLimits:
        $ref: '#/definitions/SpeedLimit'
  SpeedLimit:
    type: object
    properties:
      type:
        type: integer
      velocity:
        type: integer
  Geometry:
    type: object
    properties:
      direction:
        type: string
      extent:
        type: integer
      laneWidth:
        type: integer
      circle:
        $ref: '#/definitions/Circle'
  OldRegion:
    type: object
    properties:
      direction:
        type: string
      extent:
        type: integer
      area:
        type: string
      regionPoint:
        $ref: '#/definitions/RegionPoint'
      circle:
        $ref: '#/definitions/Circle'
      shapePoint:
        $ref: '#/definitions/ShapePoint'
  Circle:
    type: object
    properties:
      position:
        $ref: '#/definitions/J2735Position3D'
      radius:
        type: integer
      units:
        type: integer
  ShapePoint:
    type: object
    properties:
      position:
        $ref: '#/definitions/J2735Position3D'
      directionality:
        type: integer
      nodeType:
        type: string
      computedLane:
        $ref: '#/definitions/ComputedLane'
      nodexy:
        type: array
        items:
          $ref: '#/definitions/NodeXY'
  RegionPoint:
    type: object
    properties:
      position:
        $ref: '#/definitions/J2735Position3D'
      scale:
        type: integer
      regionList:
        type: array
        items:
          $ref: '#/definitions/RegionList'
  RegionList:
    type: object
    properties:
      xOffset:
        type: integer
      yOffset:
        type: integer
      zOffset:
        type: integer
  J2735Position3D:
    type: object
    properties:
      latitude:
        type: number
      longitude:
        type: number
      elevation:
        type: integer
  NodeXY:
    type: object
    properties:
      delta:
        type: string
      nodeLat:
        type: integer
      nodeLong:
        type: integer
      x:
        type: integer
      'y':
        type: integer
      attributes:
        $ref: '#/definitions/Attribute'
  ITISObj:
    type: object
    properties:
      ITISCodes:
        type: integer
      ITIStext:
        type: string
  SNMP:
    type: object
    properties:
      rsuid:
        type: string
      msgid:
        type: string
      mode:
        type: string
      channel:
        type: string
      interval:
        type: string
      deliverystart:
        type: string
      deliverystop:
        type: string
      enable:
        type: string
      status:
        type: string
  RSU:
    type: object
    properties:
      rsuTarget:
        type: string
      rsuUsername:
        type: string
      rsuPassword:
        type: string
      rsuRetries:
        type: string
      rsuTimeout:
        type: string
  SDW:
    type: object
    properties:
      nwCorner:
        type: object
        properties:
          latitude:
            type: string
          longitude:
            type: string
      seCorner:
        type: object
        properties:
          latitude:
            type: string
          longitude:
            type: string
  PDM:
    type: object
    properties:
      sampleStart:
        type: string
      sampleEnd:
        type: string
      directions:
        type: string
      termChoice:
        type: string
      termTime:
        type: string
      termDistance:
        type: string
      snapshotChoice:
        type: string
      minSnapshotTime:
        type: string
      maxSnapshotTime:
        type: string
      minSnapshotDistance:
        type: string
      maxSnapshotDistance:
        type: string
      snapshotMinSpeed:
        type: string
      snapshotMaxSpeed:
        type: string
      txInterval:
        type: string
      vehicleStatusRequestList:
        type: array
        items:
          $ref: '#/definitions/VehicleStatusRequest'
  VehicleStatusRequest:
    type: object
    properties:
      tag:
        type: string
      subTag:
        type: string
      lessThenValue:
        type: string
      moreThenValue:
        type: string
      sendAll:
        type: string
      status:
        type: string
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
